# Use official Node.js image
FROM node:18-alpine

# Set working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json first (to optimize Docker caching)
COPY package*.json ./

# Install dependencies with production mode
RUN npm install --only=production

# Copy the rest of the application files
COPY . .



# Expose port 9090
EXPOSE 2880

# Start the application (ensure "start" script exists in package.json)
CMD ["npm", "start"]
